// All countries with ISO codes and French names for country-flag-icons library
export interface Country {
  code: string;      // ISO 3166-1 alpha-2 code (BJ, FR, US, etc.)
  name: string;      // Country name in French
  dialCode: string;  // International dial code
}

export const COUNTRIES: Country[] = [
  { code: 'AD', name: 'Andorre', dialCode: '+376' },
  { code: 'AE', name: 'Émirats arabes unis', dialCode: '+971' },
  { code: 'AF', name: 'Afghanistan', dialCode: '+93' },
  { code: 'AG', name: 'Antigua-et-Barbuda', dialCode: '+1268' },
  { code: 'AI', name: 'Anguilla', dialCode: '+1264' },
  { code: 'AL', name: 'Albanie', dialCode: '+355' },
  { code: 'AM', name: 'Arménie', dialCode: '+374' },
  { code: 'AO', name: 'Angola', dialCode: '+244' },
  { code: 'AQ', name: 'Antarctique', dialCode: '+672' },
  { code: 'AR', name: 'Argentine', dialCode: '+54' },
  { code: 'AS', name: 'Samoa américaines', dialCode: '+1684' },
  { code: 'AT', name: 'Autriche', dialCode: '+43' },
  { code: 'AU', name: 'Australie', dialCode: '+61' },
  { code: 'AW', name: 'Aruba', dialCode: '+297' },
  { code: 'AX', name: 'Åland', dialCode: '+358' },
  { code: 'AZ', name: 'Azerbaïdjan', dialCode: '+994' },
  { code: 'BA', name: 'Bosnie-Herzégovine', dialCode: '+387' },
  { code: 'BB', name: 'Barbade', dialCode: '+1246' },
  { code: 'BD', name: 'Bangladesh', dialCode: '+880' },
  { code: 'BE', name: 'Belgique', dialCode: '+32' },
  { code: 'BF', name: 'Burkina Faso', dialCode: '+226' },
  { code: 'BG', name: 'Bulgarie', dialCode: '+359' },
  { code: 'BH', name: 'Bahreïn', dialCode: '+973' },
  { code: 'BI', name: 'Burundi', dialCode: '+257' },
  { code: 'BJ', name: 'Bénin', dialCode: '+229' },
  { code: 'BL', name: 'Saint-Barthélemy', dialCode: '+590' },
  { code: 'BM', name: 'Bermudes', dialCode: '+1441' },
  { code: 'BN', name: 'Brunei', dialCode: '+673' },
  { code: 'BO', name: 'Bolivie', dialCode: '+591' },
  { code: 'BQ', name: 'Pays-Bas caribéens', dialCode: '+599' },
  { code: 'BR', name: 'Brésil', dialCode: '+55' },
  { code: 'BS', name: 'Bahamas', dialCode: '+1242' },
  { code: 'BT', name: 'Bhoutan', dialCode: '+975' },
  { code: 'BV', name: 'Île Bouvet', dialCode: '+47' },
  { code: 'BW', name: 'Botswana', dialCode: '+267' },
  { code: 'BY', name: 'Biélorussie', dialCode: '+375' },
  { code: 'BZ', name: 'Belize', dialCode: '+501' },
  { code: 'CA', name: 'Canada', dialCode: '+1' },
  { code: 'CC', name: 'Îles Cocos (Keeling)', dialCode: '+61' },
  { code: 'CD', name: 'Congo (RDC)', dialCode: '+243' },
  { code: 'CF', name: 'République centrafricaine', dialCode: '+236' },
  { code: 'CG', name: 'Congo (République)', dialCode: '+242' },
  { code: 'CH', name: 'Suisse', dialCode: '+41' },
  { code: 'CI', name: 'Côte d\'Ivoire', dialCode: '+225' },
  { code: 'CK', name: 'Îles Cook', dialCode: '+682' },
  { code: 'CL', name: 'Chili', dialCode: '+56' },
  { code: 'CM', name: 'Cameroun', dialCode: '+237' },
  { code: 'CN', name: 'Chine', dialCode: '+86' },
  { code: 'CO', name: 'Colombie', dialCode: '+57' },
  { code: 'CR', name: 'Costa Rica', dialCode: '+506' },
  { code: 'CU', name: 'Cuba', dialCode: '+53' },
  { code: 'CV', name: 'Cap-Vert', dialCode: '+238' },
  { code: 'CW', name: 'Curaçao', dialCode: '+599' },
  { code: 'CX', name: 'Île Christmas', dialCode: '+61' },
  { code: 'CY', name: 'Chypre', dialCode: '+357' },
  { code: 'CZ', name: 'Tchéquie', dialCode: '+420' },
  { code: 'DE', name: 'Allemagne', dialCode: '+49' },
  { code: 'DJ', name: 'Djibouti', dialCode: '+253' },
  { code: 'DK', name: 'Danemark', dialCode: '+45' },
  { code: 'DM', name: 'Dominique', dialCode: '+1767' },
  { code: 'DO', name: 'République dominicaine', dialCode: '+1' },
  { code: 'DZ', name: 'Algérie', dialCode: '+213' },
  { code: 'EC', name: 'Équateur', dialCode: '+593' },
  { code: 'EE', name: 'Estonie', dialCode: '+372' },
  { code: 'EG', name: 'Égypte', dialCode: '+20' },
  { code: 'EH', name: 'Sahara occidental', dialCode: '+212' },
  { code: 'ER', name: 'Érythrée', dialCode: '+291' },
  { code: 'ES', name: 'Espagne', dialCode: '+34' },
  { code: 'ET', name: 'Éthiopie', dialCode: '+251' },
  { code: 'FI', name: 'Finlande', dialCode: '+358' },
  { code: 'FJ', name: 'Fidji', dialCode: '+679' },
  { code: 'FK', name: 'Îles Malouines', dialCode: '+500' },
  { code: 'FM', name: 'Micronésie', dialCode: '+691' },
  { code: 'FO', name: 'Îles Féroé', dialCode: '+298' },
  { code: 'FR', name: 'France', dialCode: '+33' },
  { code: 'GA', name: 'Gabon', dialCode: '+241' },
  { code: 'GB', name: 'Royaume-Uni', dialCode: '+44' },
  { code: 'GD', name: 'Grenade', dialCode: '+1473' },
  { code: 'GE', name: 'Géorgie', dialCode: '+995' },
  { code: 'GF', name: 'Guyane française', dialCode: '+594' },
  { code: 'GG', name: 'Guernesey', dialCode: '+44' },
  { code: 'GH', name: 'Ghana', dialCode: '+233' },
  { code: 'GI', name: 'Gibraltar', dialCode: '+350' },
  { code: 'GL', name: 'Groenland', dialCode: '+299' },
  { code: 'GM', name: 'Gambie', dialCode: '+220' },
  { code: 'GN', name: 'Guinée', dialCode: '+224' },
  { code: 'GP', name: 'Guadeloupe', dialCode: '+590' },
  { code: 'GQ', name: 'Guinée équatoriale', dialCode: '+240' },
  { code: 'GR', name: 'Grèce', dialCode: '+30' },
  { code: 'GS', name: 'Géorgie du Sud et îles Sandwich du Sud', dialCode: '+500' },
  { code: 'GT', name: 'Guatemala', dialCode: '+502' },
  { code: 'GU', name: 'Guam', dialCode: '+1671' },
  { code: 'GW', name: 'Guinée-Bissau', dialCode: '+245' },
  { code: 'GY', name: 'Guyana', dialCode: '+592' },
  { code: 'HK', name: 'Hong Kong', dialCode: '+852' },
  { code: 'HM', name: 'Îles Heard et McDonald', dialCode: '+672' },
  { code: 'HN', name: 'Honduras', dialCode: '+504' },
  { code: 'HR', name: 'Croatie', dialCode: '+385' },
  { code: 'HT', name: 'Haïti', dialCode: '+509' },
  { code: 'HU', name: 'Hongrie', dialCode: '+36' },
  { code: 'ID', name: 'Indonésie', dialCode: '+62' },
  { code: 'IE', name: 'Irlande', dialCode: '+353' },
  { code: 'IL', name: 'Israël', dialCode: '+972' },
  { code: 'IM', name: 'Île de Man', dialCode: '+44' },
  { code: 'IN', name: 'Inde', dialCode: '+91' },
  { code: 'IO', name: 'Territoire britannique de l\'océan Indien', dialCode: '+246' },
  { code: 'IQ', name: 'Irak', dialCode: '+964' },
  { code: 'IR', name: 'Iran', dialCode: '+98' },
  { code: 'IS', name: 'Islande', dialCode: '+354' },
  { code: 'IT', name: 'Italie', dialCode: '+39' },
  { code: 'JE', name: 'Jersey', dialCode: '+44' },
  { code: 'JM', name: 'Jamaïque', dialCode: '+1876' },
  { code: 'JO', name: 'Jordanie', dialCode: '+962' },
  { code: 'JP', name: 'Japon', dialCode: '+81' },
  { code: 'KE', name: 'Kenya', dialCode: '+254' },
  { code: 'KG', name: 'Kirghizistan', dialCode: '+996' },
  { code: 'KH', name: 'Cambodge', dialCode: '+855' },
  { code: 'KI', name: 'Kiribati', dialCode: '+686' },
  { code: 'KM', name: 'Comores', dialCode: '+269' },
  { code: 'KN', name: 'Saint-Christophe-et-Niévès', dialCode: '+1869' },
  { code: 'KP', name: 'Corée du Nord', dialCode: '+850' },
  { code: 'KR', name: 'Corée du Sud', dialCode: '+82' },
  { code: 'KW', name: 'Koweït', dialCode: '+965' },
  { code: 'KY', name: 'Îles Caïmans', dialCode: '+1345' },
  { code: 'KZ', name: 'Kazakhstan', dialCode: '+7' },
  { code: 'LA', name: 'Laos', dialCode: '+856' },
  { code: 'LB', name: 'Liban', dialCode: '+961' },
  { code: 'LC', name: 'Sainte-Lucie', dialCode: '+1758' },
  { code: 'LI', name: 'Liechtenstein', dialCode: '+423' },
  { code: 'LK', name: 'Sri Lanka', dialCode: '+94' },
  { code: 'LR', name: 'Liberia', dialCode: '+231' },
  { code: 'LS', name: 'Lesotho', dialCode: '+266' },
  { code: 'LT', name: 'Lituanie', dialCode: '+370' },
  { code: 'LU', name: 'Luxembourg', dialCode: '+352' },
  { code: 'LV', name: 'Lettonie', dialCode: '+371' },
  { code: 'LY', name: 'Libye', dialCode: '+218' },
  { code: 'MA', name: 'Maroc', dialCode: '+212' },
  { code: 'MC', name: 'Monaco', dialCode: '+377' },
  { code: 'MD', name: 'Moldavie', dialCode: '+373' },
  { code: 'ME', name: 'Monténégro', dialCode: '+382' },
  { code: 'MF', name: 'Saint-Martin', dialCode: '+590' },
  { code: 'MG', name: 'Madagascar', dialCode: '+261' },
  { code: 'MH', name: 'Îles Marshall', dialCode: '+692' },
  { code: 'MK', name: 'Macédoine', dialCode: '+389' },
  { code: 'ML', name: 'Mali', dialCode: '+223' },
  { code: 'MM', name: 'Myanmar', dialCode: '+95' },
  { code: 'MN', name: 'Mongolie', dialCode: '+976' },
  { code: 'MO', name: 'Macao', dialCode: '+853' },
  { code: 'MP', name: 'Îles Mariannes du Nord', dialCode: '+1670' },
  { code: 'MQ', name: 'Martinique', dialCode: '+596' },
  { code: 'MR', name: 'Mauritanie', dialCode: '+222' },
  { code: 'MS', name: 'Montserrat', dialCode: '+1664' },
  { code: 'MT', name: 'Malte', dialCode: '+356' },
  { code: 'MU', name: 'Île Maurice', dialCode: '+230' },
  { code: 'MV', name: 'Maldives', dialCode: '+960' },
  { code: 'MW', name: 'Malawi', dialCode: '+265' },
  { code: 'MX', name: 'Mexique', dialCode: '+52' },
  { code: 'MY', name: 'Malaisie', dialCode: '+60' },
  { code: 'MZ', name: 'Mozambique', dialCode: '+258' },
  { code: 'NA', name: 'Namibie', dialCode: '+264' },
  { code: 'NC', name: 'Nouvelle-Calédonie', dialCode: '+687' },
  { code: 'NE', name: 'Niger', dialCode: '+227' },
  { code: 'NF', name: 'Île Norfolk', dialCode: '+672' },
  { code: 'NG', name: 'Nigeria', dialCode: '+234' },
  { code: 'NI', name: 'Nicaragua', dialCode: '+505' },
  { code: 'NL', name: 'Pays-Bas', dialCode: '+31' },
  { code: 'NO', name: 'Norvège', dialCode: '+47' },
  { code: 'NP', name: 'Népal', dialCode: '+977' },
  { code: 'NR', name: 'Nauru', dialCode: '+674' },
  { code: 'NU', name: 'Niue', dialCode: '+683' },
  { code: 'NZ', name: 'Nouvelle-Zélande', dialCode: '+64' },
  { code: 'OM', name: 'Oman', dialCode: '+968' },
  { code: 'PA', name: 'Panama', dialCode: '+507' },
  { code: 'PE', name: 'Pérou', dialCode: '+51' },
  { code: 'PF', name: 'Polynésie française', dialCode: '+689' },
  { code: 'PG', name: 'Papouasie-Nouvelle-Guinée', dialCode: '+675' },
  { code: 'PH', name: 'Philippines', dialCode: '+63' },
  { code: 'PK', name: 'Pakistan', dialCode: '+92' },
  { code: 'PL', name: 'Pologne', dialCode: '+48' },
  { code: 'PM', name: 'Saint-Pierre-et-Miquelon', dialCode: '+508' },
  { code: 'PN', name: 'Îles Pitcairn', dialCode: '+870' },
  { code: 'PR', name: 'Porto Rico', dialCode: '+1787' },
  { code: 'PS', name: 'Palestine', dialCode: '+970' },
  { code: 'PT', name: 'Portugal', dialCode: '+351' },
  { code: 'PW', name: 'Palaos', dialCode: '+680' },
  { code: 'PY', name: 'Paraguay', dialCode: '+595' },
  { code: 'QA', name: 'Qatar', dialCode: '+974' },
  { code: 'RE', name: 'Réunion', dialCode: '+262' },
  { code: 'RO', name: 'Roumanie', dialCode: '+40' },
  { code: 'RS', name: 'Serbie', dialCode: '+381' },
  { code: 'RU', name: 'Russie', dialCode: '+7' },
  { code: 'RW', name: 'Rwanda', dialCode: '+250' },
  { code: 'SA', name: 'Arabie saoudite', dialCode: '+966' },
  { code: 'SB', name: 'Îles Salomon', dialCode: '+677' },
  { code: 'SC', name: 'Seychelles', dialCode: '+248' },
  { code: 'SD', name: 'Soudan', dialCode: '+249' },
  { code: 'SE', name: 'Suède', dialCode: '+46' },
  { code: 'SG', name: 'Singapour', dialCode: '+65' },
  { code: 'SH', name: 'Sainte-Hélène', dialCode: '+290' },
  { code: 'SI', name: 'Slovénie', dialCode: '+386' },
  { code: 'SJ', name: 'Svalbard et Jan Mayen', dialCode: '+47' },
  { code: 'SK', name: 'Slovaquie', dialCode: '+421' },
  { code: 'SL', name: 'Sierra Leone', dialCode: '+232' },
  { code: 'SM', name: 'Saint-Marin', dialCode: '+378' },
  { code: 'SN', name: 'Sénégal', dialCode: '+221' },
  { code: 'SO', name: 'Somalie', dialCode: '+252' },
  { code: 'SR', name: 'Suriname', dialCode: '+597' },
  { code: 'SS', name: 'Soudan du Sud', dialCode: '+211' },
  { code: 'ST', name: 'São Tomé-et-Príncipe', dialCode: '+239' },
  { code: 'SV', name: 'Salvador', dialCode: '+503' },
  { code: 'SX', name: 'Sint-Maarten', dialCode: '+1721' },
  { code: 'SY', name: 'Syrie', dialCode: '+963' },
  { code: 'SZ', name: 'Eswatini', dialCode: '+268' },
  { code: 'TC', name: 'Îles Turques-et-Caïques', dialCode: '+1649' },
  { code: 'TD', name: 'Tchad', dialCode: '+235' },
  { code: 'TF', name: 'Terres australes françaises', dialCode: '+262' },
  { code: 'TG', name: 'Togo', dialCode: '+228' },
  { code: 'TH', name: 'Thaïlande', dialCode: '+66' },
  { code: 'TJ', name: 'Tadjikistan', dialCode: '+992' },
  { code: 'TK', name: 'Tokelau', dialCode: '+690' },
  { code: 'TL', name: 'Timor oriental', dialCode: '+670' },
  { code: 'TM', name: 'Turkménistan', dialCode: '+993' },
  { code: 'TN', name: 'Tunisie', dialCode: '+216' },
  { code: 'TO', name: 'Tonga', dialCode: '+676' },
  { code: 'TR', name: 'Turquie', dialCode: '+90' },
  { code: 'TT', name: 'Trinité-et-Tobago', dialCode: '+1868' },
  { code: 'TV', name: 'Tuvalu', dialCode: '+688' },
  { code: 'TW', name: 'Taïwan', dialCode: '+886' },
  { code: 'TZ', name: 'Tanzanie', dialCode: '+255' },
  { code: 'UA', name: 'Ukraine', dialCode: '+380' },
  { code: 'UG', name: 'Ouganda', dialCode: '+256' },
  { code: 'US', name: 'États-Unis', dialCode: '+1' },
  { code: 'UY', name: 'Uruguay', dialCode: '+598' },
  { code: 'UZ', name: 'Ouzbékistan', dialCode: '+998' },
  { code: 'VA', name: 'Vatican', dialCode: '+39' },
  { code: 'VC', name: 'Saint-Vincent-et-les-Grenadines', dialCode: '+1784' },
  { code: 'VE', name: 'Venezuela', dialCode: '+58' },
  { code: 'VG', name: 'Îles Vierges britanniques', dialCode: '+1284' },
  { code: 'VI', name: 'Îles Vierges américaines', dialCode: '+1340' },
  { code: 'VN', name: 'Vietnam', dialCode: '+84' },
  { code: 'VU', name: 'Vanuatu', dialCode: '+678' },
  { code: 'WF', name: 'Wallis-et-Futuna', dialCode: '+681' },
  { code: 'WS', name: 'Samoa', dialCode: '+685' },
  { code: 'YE', name: 'Yémen', dialCode: '+967' },
  { code: 'YT', name: 'Mayotte', dialCode: '+262' },
  { code: 'ZA', name: 'Afrique du Sud', dialCode: '+27' },
  { code: 'ZM', name: 'Zambie', dialCode: '+260' },
  { code: 'ZW', name: 'Zimbabwe', dialCode: '+263' },
].sort((a, b) => a.name.localeCompare(b.name, 'fr'));
